language: python
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - "pip install ."
  - "pip install six"
  - "pip install mock"
  - "pip install pep8"
script:
  - nosetests tests/
  - pep8 --max-line-length=120
